# Versão da API Utilizada no Kubernetes
apiVersion: apps/v1
kind: Deployment
# Cria o deployment
metadata:
  name: conversao-distancia
# Cria a quantidade de replicas
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: conversao-distancia
  template:
    metadata:
      labels:
        app: conversao-distancia
    spec:
      containers:
      - name: conversao-distancia
        image: ricardogomes335/conversao-distancia:v1
        ports:
        - containerPort: 5000
---

# Versão nodePort
apiVersion: v1
kind: Service
metadata:
  name: conversao-distancia
spec:
  selector:
    app: conversao-distancia
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
  type: NodePort

