# Versão da API Utilizada no Kubernetes
apiVersion: apps/v1
kind: Deployment
# Cria o deployment
metadata:
  name: conversao-distancia
# Cria a quantidade de replicas
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: conversao-distancia
  template:
    metadata:
      labels:
        app: conversao-distancia
    spec:
      containers:
      - name: conversao-distancia
        image: ricardogomes335/conversao-distancia:v1
        ports:
        - containerPort: 5000
---

# Versão da API Utilizada no Kubernetes
apiVersion: v1
kind: Service
metadata:
  name: conversao-distancia
spec:
  selector:
    app: conversao-distancia
  ports:
    - port: 80
      targetPort: 5000
<<<<<<< Tabnine <<<<<<<
    type: NodePort
>>>>>>> Tabnine >>>>>>># {"conversationId":"1d862791-a7eb-47d0-9ca9-46e195b8d995","source":"instruct"}

